Title: Following your steps resulted in the following exc...
Date: 2014-01-29 17:09:58.005
Category: blog
Tags: 
Slug: Following-your-steps-resulted-in-the-following-exc...
Authors: Steve Theodore
Summary: pending

Following your steps resulted in the following exception: TypeLoadException: Could not load type 'IronPython.Runtime.PythonContext' from assembly 'IronPython' during the CreateEngine() call.

